### ISSUE TITLE
Tripling in dummy_ensemble

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/FabDummy#2]
Running `fabsim localhost dummy_ensemble:dummy_test` results in the submission of 3 jobs instead of 1. The 3 jobs have labels `d1`, `d2` and `d3` respectively.

I also tried this on a machine with new installation of FabSim and FabDummy. So it does not seem to be a problem in the user-specific config files.

**Comment by djgroen** [comment]
Ensembles imply multiple runs. In this case it runs one instance of input set d1, d2 and d3 respectively.

So this is actually desired behavior ;).

**Comment by arindamsaha1507** [comment]
Ah, so it goes through the sweep directory! Understood.
